## global config
remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en"
title                    : "mox blog"
title_separator          : "|"
name                     : "mox"
description              : "Blog about Linux, DevOps, Security, etc."
url                      : "https://mox.sh"
repository               : "javimox/javimox.github.io"
masthead_title           : "mox blog"
breadcrumbs              : true
words_per_minute         : 200
comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "staticman", "utterances", "custom"
  disqus:
    shortname            : "jmox"
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : "algolia"
algolia:
  application_id         : "O8SG8MN4LE"
  index_name             : "prod_MOXSH"
  search_only_api_key    : "79e49dd8462d985072847bab4a8c1e31"
  powered_by             : true
  files_to_exclude: # exclude files from indexing
    - index.html
    - index.md
    - excluded-file.html
    - _posts/2017-11-28-post-exclude-search.md 
    - _drafts/*.md

# SEO Related
google_site_verification : 3uYX0hRu60WvgxAjONUjpayiXQOe1Knenbr0s-gpgk0
bing_site_verification   :
yandex_site_verification :

# Social Sharing
twitter:
  username               : ""
og_image                 : "/assets/images/bio-photo.png"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - https://github.com/javimox

# Analytics
analytics:
  provider               : google # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-163407120-1

# Site Author
author:
  name             : "jmox"
  avatar           : "/assets/images/bio-photo.png"
  bio              : "I am `$(whoami)`.<br />About myself, I can say:<br />`lslogins \\`<br />`--noheadings \\`<br />`-o=GECOS -l $(whoami)`"
  location         : "$HOME"
  links:
    - label: "E-mail"
      icon: "fas fa-fw fa-at"
      url: "mailto:jmox@pm.me"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/javimox"
    - label: "Keybase"
      icon: "fab fa-fw fa-keybase"
      url: "https://keybase.io/javimox"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/javimox"

# Reading Files
include:
  - .htaccess
  - .well-known
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Liquid
strict_front_matter: true
liquid:
  error_mode: strict

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Scripts
after_footer_scripts:
  - /assets/js/go-to-the-top.js
  - /assets/js/cookie-consent.js

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 4 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections # _category dir
collections:
  category:
    output: true

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      comments: true
      toc: true
      toc_label: "Content"
      toc_sticky: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _category
  - scope:
      path: ""
      type: category
    values:
      layout: "category-toc"
